### ISSUE TITLE
Como rodar o projeto no Heroku

### ISSUE THREAD

**Issue by alissonandrade2020** [andreadcsousa/rocketseat_nlw6_discover#1]
Boa tarde Andre!

pode me ajudar a subir a aplicação ?

ele pega na vercel ?

**Comment by andreadcsousa** [comment]
Olá, na vercel eu não consegui e na heroku tem que criar um arquivo para conseguir mostrar o projeto lá.

- Crie o arquivo Procfile, no seu repositório do github: https://github.com/andreadcsousa/rocketseat_nlw6_discover/blob/main/Procfile
- No heroku, você precisa ir nas configurações do app, em Settings > Buildpacks e marcar "heroku/nodejs"
